CREATE TABLE IF NOT EXISTS records (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id TEXT NOT NULL UNIQUE,
    input_photo_path TEXT NOT NULL,
    input_photo_sha256 TEXT NOT NULL,
    search_provider TEXT NOT NULL,
    reverse_match_type TEXT NOT NULL,
    matched_page_url TEXT NOT NULL,
    candidate_image_url TEXT,
    is_social INTEGER NOT NULL CHECK (is_social IN (0, 1)),
    face_status TEXT NOT NULL,
    face_model TEXT,
    face_distance REAL,
    face_threshold REAL,
    human_confirmed INTEGER NOT NULL CHECK (human_confirmed = 1),
    confirmed_by TEXT NOT NULL,
    storage_root_hash TEXT NOT NULL,
    storage_tx_hash TEXT,
    chain_id INTEGER NOT NULL CHECK (chain_id = 16602),
    contract_address TEXT NOT NULL,
    chain_record_id TEXT NOT NULL,
    chain_tx_hash TEXT NOT NULL,
    chain_block_number INTEGER NOT NULL,
    readback_verified INTEGER NOT NULL CHECK (readback_verified IN (0, 1)),
    created_at TEXT NOT NULL,
    UNIQUE (chain_id, contract_address, chain_record_id)
);
